	IMPORT lcd_init
	IMPORT lcd_reset
	IMPORT FF40_R
	IMPORT FF40_W
	IMPORT FF41_R
	IMPORT FF41_W
	IMPORT FF42_R
	IMPORT FF42_W
	IMPORT FF43_R
	IMPORT FF43_W
	IMPORT FF44_R
	IMPORT FF45_R
	IMPORT FF45_W
	IMPORT FF47_R
	IMPORT FF47_W
	IMPORT FF48_R
	IMPORT FF48_W
	IMPORT FF49_R
	IMPORT FF49_W
	IMPORT FF4A_R
	IMPORT FF4A_W
	IMPORT FF4B_R
	IMPORT FF4B_W
	IMPORT vram_W
	IMPORT vram_W2
	IMPORT agb_nt_map
;	IMPORT VRAM_chr
	IMPORT vram_map
	IMPORT debug_
	IMPORT map_palette
	IMPORT newframe
	IMPORT agb_pal
	IMPORT lcdstate
;	IMPORT writeBG
	IMPORT oambuffer
	IMPORT resetlcdregs
	END
